services:
  audio_extractor_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio_extractor_api
    ports:
      - "8000:8000"
    environment:
      API_KEY: ""
    restart: unless-stopped
